# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            ''
tagline:          ''
description:      'Rishabh Ranawat. Keeping track of what I read/learn.'
baseurl:          ''

author:
  name:           'Rishabh Ranawat'
  url:            https://twitter.com/rishabhranawat

paginate:         1

# Custom vars
version:          2.1.0


gems: [jekyll-gist]