# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            
tagline:          'Write to Learn'
description:      'Thoughts as I read through material.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Rishabh Ranawat'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems: [jekyll-gist]